{ colors }:

{
  "fish/conf.d/desktop-theme.fish" = ''
    # Generated by desktop.theme.
    function fish_prompt
        set_color ${builtins.replaceStrings [ "#" ] [ "" ] colors.accent}
        printf '%s@%s ' $USER (prompt_hostname)
        set_color ${builtins.replaceStrings [ "#" ] [ "" ] colors.foreground}
        printf '%s' (prompt_pwd)
        set_color ${builtins.replaceStrings [ "#" ] [ "" ] colors.muted}
        printf ' %% '
        set_color normal
    end
  '';
}
