{ colors }:

{
  "ghostty/theme-options" = ''
    # Generated by desktop.theme.
    font-family = Terminus
    font-family = DejaVu Sans Mono
    font-family = monospace
    font-size = 12.5
    background-opacity = 1
    background-blur = false
    cursor-style = block
    cursor-style-blink = false
    window-padding-x = 6
    window-padding-y = 6
  '';

  "ghostty/themes/desktop-theme" = ''
    # Generated by desktop.theme.
    palette = 0=${colors.background}
    palette = 1=${colors.error}
    palette = 2=#78947f
    palette = 3=${colors.warning}
    palette = 4=${colors.borderActive}
    palette = 5=#887583
    palette = 6=${colors.accent}
    palette = 7=${colors.foreground}
    palette = 8=${colors.muted}
    palette = 9=#c77a6d
    palette = 10=#91aa96
    palette = 11=#d2b06e
    palette = 12=#86aab3
    palette = 13=#9c8797
    palette = 14=#8ab6bc
    palette = 15=#eef0ef
    background = ${colors.background}
    foreground = ${colors.foreground}
    cursor-color = ${colors.accent}
    cursor-text = ${colors.background}
    selection-background = ${colors.border}
    selection-foreground = ${colors.foreground}
  '';
}
