{ colors }:

let
  settings = ''
    [Settings]
    gtk-theme-name=adw-gtk3-dark
    gtk-application-prefer-dark-theme=1
    gtk-icon-theme-name=Adwaita
    gtk-cursor-theme-name=Adwaita
    gtk-cursor-theme-size=24
    gtk-font-name=DejaVu Sans 10
  '';
  css = ''
    /* Generated by desktop.theme. Keep overrides conservative for libadwaita. */
    @define-color theme_bg_color ${colors.background};
    @define-color theme_base_color ${colors.panel};
    @define-color theme_fg_color ${colors.foreground};
    @define-color theme_text_color ${colors.foreground};
    @define-color theme_selected_bg_color ${colors.accentDim};
    @define-color theme_selected_fg_color ${colors.foreground};
    @define-color accent_bg_color ${colors.accentDim};
    @define-color accent_color ${colors.accent};
    @define-color accent_fg_color ${colors.foreground};
    @define-color destructive_bg_color ${colors.error};
    @define-color destructive_color ${colors.error};

    tooltip, popover > contents, menu, .menu { border-radius: 0; }
    button, entry, spinbutton, dropdown > button { border-radius: 2px; }
    selection { background-color: ${colors.accentDim}; color: ${colors.foreground}; }
  '';
in
{
  "gtk-3.0/settings.ini" = settings;
  "gtk-4.0/settings.ini" = settings;
  "gtk-3.0/gtk.css" = css;
  "gtk-4.0/gtk.css" = css;
}
