{ colors }:

let
  rgba = color: alpha:
    let
      hex = builtins.replaceStrings [ "#" ] [ "" ] color;
      r = builtins.substring 0 2 hex;
      g = builtins.substring 2 2 hex;
      b = builtins.substring 4 2 hex;
    in "rgba(${r}${g}${b}${alpha})";
in
{
  "hypr/theme-hyprlock.conf" = ''
    # Generated by desktop.theme.
    general {
        hide_cursor = true
        ignore_empty_input = true
    }

    background {
        monitor =
        color = ${rgba colors.background "ff"}
        blur_passes = 0
    }

    label {
        monitor =
        text = cmd[update:1000] date +"%H:%M"
        font_family = Terminus
        font_size = 64
        color = ${rgba colors.foreground "ff"}
        position = 0, 90
        halign = center
        valign = center
    }

    label {
        monitor =
        text = cmd[update:60000] date +"%A, %d %B"
        font_family = Terminus
        font_size = 16
        color = ${rgba colors.muted "ff"}
        position = 0, 42
        halign = center
        valign = center
    }

    input-field {
        monitor =
        size = 280, 34
        outline_thickness = 1
        rounding = 0
        dots_size = 0.18
        dots_spacing = 0.3
        outer_color = ${rgba colors.border "ff"}
        inner_color = ${rgba colors.panel "ff"}
        font_color = ${rgba colors.foreground "ff"}
        fail_color = ${rgba colors.error "ff"}
        check_color = ${rgba colors.borderActive "ff"}
        placeholder_text = password:
        position = 0, -35
        halign = center
        valign = center
    }
  '';
}
