{ colors }:

let
  hex = color: builtins.replaceStrings [ "#" ] [ "" ] color;
  rgba = color: "rgba(${hex color}FF)";
in
{
  "hypr/config/theme.lua" = ''
    -- Generated by desktop.theme; edit nix/themes/openbsd-dark instead.
    colors = {
        accent = "${rgba colors.accent}",
        accentAlt = "${rgba colors.borderActive}",
        inactiveBord = "${rgba colors.border}",
        background = "${rgba colors.background}",
        foreground = "${rgba colors.foreground}",
        error = "${rgba colors.error}",
        surface = "${rgba colors.surface}",
        groupLocked = "${rgba colors.warning}",
    }

    theme = { wallpaper_command = "awww clear ${hex colors.background}" }

    hl.config({
        general = {
            gaps_in = 3,
            gaps_out = 5,
            border_size = 1,
            col = {
                active_border = colors.accentAlt,
                inactive_border = colors.inactiveBord,
            },
        },
        group = {
            col = {
                border_active = colors.accentAlt,
                border_inactive = colors.inactiveBord,
                border_locked_active = colors.groupLocked,
                border_locked_inactive = colors.inactiveBord,
            },
            groupbar = { col = {
                active = colors.accentAlt,
                inactive = colors.inactiveBord,
                locked_active = colors.groupLocked,
                locked_inactive = colors.inactiveBord,
            } },
        },
        decoration = {
            rounding = 0,
            active_opacity = 1.0,
            inactive_opacity = 1.0,
            fullscreen_opacity = 1.0,
            blur = { enabled = false },
            shadow = { enabled = false },
        },
    })

    hl.animation({ leaf = "global", enabled = false })
  '';
}
