{ colors }:

let
  rgb = colors.rgb;
  section = name: background: foreground: ''
    [Colors:${name}]
    BackgroundAlternate=${rgb.surface}
    BackgroundNormal=${background}
    DecorationFocus=${rgb.borderActive}
    DecorationHover=${rgb.accent}
    ForegroundActive=${rgb.accent}
    ForegroundInactive=${rgb.muted}
    ForegroundLink=${rgb.accent}
    ForegroundNegative=${rgb.error}
    ForegroundNeutral=${rgb.warning}
    ForegroundNormal=${foreground}
    ForegroundPositive=${rgb.accent}
    ForegroundVisited=${rgb.borderActive}
  '';
in
{
  "qt6ct/colors/desktop-theme.conf" = ''
    [ColorEffects:Disabled]
    Color=96,96,96
    ColorAmount=0
    ColorEffect=0
    ContrastAmount=0.65
    ContrastEffect=1
    IntensityAmount=0.1
    IntensityEffect=2
    ${section "Button" rgb.surface rgb.foreground}
    ${section "Selection" rgb.accentDim or rgb.border rgb.foreground}
    ${section "View" rgb.background rgb.foreground}
    ${section "Window" rgb.panel rgb.foreground}
    [General]
    ColorScheme=OpenBSD Dark
    Name=OpenBSD Dark
  '';

  "qt6ct/qt6ct.conf" = ''
    [Appearance]
    color_scheme_path=/home/amado/.config/qt6ct/colors/desktop-theme.conf
    custom_palette=true
    icon_theme=Papirus-Dark
    standard_dialogs=default
    style=Fusion

    [Interface]
    stylesheets=/home/amado/.config/qt6ct/openbsd-dark.qss
  '';

  "qt6ct/openbsd-dark.qss" = ''
    /* Generated by desktop.theme. */
    QWidget {
      background-color: ${colors.background};
      color: ${colors.foreground};
      selection-background-color: ${colors.accentDim};
      selection-color: ${colors.foreground};
    }
    QToolBar, QMenuBar, QStatusBar, QMenu, QToolTip, QHeaderView::section {
      background-color: ${colors.panel};
      border: 0;
    }
    QMenu, QToolTip, QAbstractItemView, QTreeView, QListView, QTableView {
      border: 1px solid ${colors.border};
    }
    QPushButton, QToolButton, QLineEdit, QTextEdit, QPlainTextEdit,
    QComboBox, QSpinBox, QDoubleSpinBox {
      background-color: ${colors.surface};
      border: 1px solid ${colors.border};
      border-radius: 0;
      padding: 2px 4px;
    }
    QPushButton:hover, QToolButton:hover, QComboBox:hover {
      border-color: ${colors.borderActive};
    }
    QPushButton:pressed, QToolButton:pressed, QMenu::item:selected,
    QTabBar::tab:selected, QAbstractItemView::item:selected {
      background-color: ${colors.accentDim};
      color: ${colors.foreground};
    }
    QTabBar::tab {
      background-color: ${colors.panel};
      border: 1px solid ${colors.border};
      border-radius: 0;
      padding: 3px 7px;
    }
    QScrollBar { background: ${colors.panel}; border: 0; }
    QScrollBar::handle { background: ${colors.border}; min-height: 20px; min-width: 8px; }
    QScrollBar::add-line, QScrollBar::sub-line { width: 0; height: 0; }
  '';
}
