{ colors }:

{
  "swaync/theme.css" = ''
    /* Generated by desktop.theme. */
    @define-color bg ${colors.background};
    @define-color bg-alt ${colors.panel};
    @define-color bg-hover ${colors.surface};
    @define-color fg ${colors.foreground};
    @define-color fg-dim ${colors.muted};
    @define-color accent ${colors.accent};
    @define-color warning ${colors.warning};
    @define-color critical ${colors.error};
    @define-color border ${colors.border};
  
    * {
        font-family: "Terminus", "Iosevka", monospace;
        font-size: 12px;
        border-radius: 0;
        --notification-icon-size: 32px;
    }

    .notification-row { outline: none; }
    .notification-row:focus, .notification-row:hover { background: @bg-hover; }

    .notification {
        background: @bg-alt;
        color: @fg;
        border: 1px solid @border;
        margin: 2px 0;
        padding: 5px 7px;
        box-shadow: none;
    }

    .notification.critical { border-color: @critical; }
    .notification-content { background: transparent; color: @fg; padding: 0; }
    .notification-content .image { margin-right: 8px; }
    .notification-content .summary { color: @fg; font-weight: bold; }
    .notification-content .body, .notification-content .time { color: @fg-dim; }

    .notification-action, .notification-default-action, .close-button {
        background: transparent;
        color: @accent;
        border: 1px solid @border;
        padding: 2px 4px;
        margin: 1px;
        min-height: 16px;
    }

    .notification-action:hover, .notification-default-action:hover, .close-button:hover {
        background: @bg-hover;
    }

    .control-center {
        background: @bg;
        border: 1px solid @border;
        box-shadow: none;
    }

    .control-center-list { background: transparent; }
    .widget-title, .widget-dnd {
        color: @fg;
        background: @bg-alt;
        border: 1px solid @border;
        margin: 2px;
        padding: 4px 6px;
    }
    .widget-title button, .widget-dnd > switch {
        color: @fg;
        background: @bg-hover;
        border: 1px solid @border;
    }
    .widget-dnd > switch:checked { background: @accent; }
    .widget-dnd > switch slider { background: @fg; }
    scrollbar slider { background: @border; min-width: 4px; min-height: 24px; }
  '';
}
