{ colors }:

{
  "waybar/theme.css" = ''
    /* Generated by desktop.theme. */
    @define-color bg ${colors.panel};
    @define-color bg-alt ${colors.surface};
    @define-color bg-hover ${colors.surface};
    @define-color fg ${colors.foreground};
    @define-color fg-dim ${colors.muted};
    @define-color accent ${colors.accent};
    @define-color accent-dim ${colors.accentDim};
    @define-color warning ${colors.warning};
    @define-color critical ${colors.error};
    @define-color border ${colors.border};
  
    * {
        font-family: "Terminus", "Iosevka", monospace;
        font-size: 14px;
        border: none;
        border-radius: 0;
        min-height: 0;
    }

    window#waybar {
        background: @bg;
        color: @fg;
        border-bottom: 1px solid @border;
        min-height: 25px;
    }

    tooltip {
        background: @bg-alt;
        color: @fg;
        border: 1px solid @border;
        border-radius: 0;
    }

    #workspaces button {
        background: transparent;
        color: @fg-dim;
        padding: 0 6px;
        margin: 0;
        border-left: 1px solid transparent;
        border-right: 1px solid transparent;
    }

    #workspaces button.active {
        background: @bg-alt;
        color: @accent;
        border-left-color: @accent;
        border-right-color: @accent;
    }

    #workspaces button:hover {
        background: @bg-alt;
        color: @fg;
    }

    #workspaces button.urgent,
    #memory.critical,
    #network.disconnected,
    #temperature.critical,
    #custom-ai-quota.critical,
    #custom-ai-quota.error {
        color: @critical;
    }

    #workspaces {
        padding: 0 3px;
        border-right: 1px solid @border;
    }

    #custom-host,
    #custom-ai-quota,
    #cpu, #memory, #temperature, #network, #bluetooth, #pulseaudio,
    #custom-kb_layout, #tray, #custom-notification, #clock {
        color: @fg;
        padding: 0 7px;
    }

    #custom-host { color: @accent; }
    #custom-ai-quota, #custom-kb_layout, #custom-notification { color: @fg-dim; }
    #custom-ai-quota { border-right: 1px solid @border; }
    #cpu, #network, #pulseaudio, #clock { border-left: 1px solid @border; }
    #memory.warning, #custom-ai-quota.warning { color: @warning; }
    #pulseaudio.muted { color: @fg-dim; }
    #tray { padding-right: 4px; }
    #tray > widget { margin: 0 2px; }
    #tray > .passive { -gtk-icon-effect: dim; }
    #tray > .needs-attention { -gtk-icon-effect: highlight; }
  '';
}
